#!/bin/bash

# Wrapper for vscode code command
function fcode() {
    # Unable to connect to VS Code server: Error in request - ENOENT /run/user/1000/vscode-ipc-*.sock
    # https://github.com/microsoft/vscode-remote-release/issues/6997#issue-1319650016
    # https://github.com/microsoft/vscode-remote-release/issues/6362#issuecomment-1046458477
    vscode_code_path=$(find $HOME/.vscode-server/ -type f -name code -executable)
    if [[ -z $vscode_code_path ]]
    then
        echo "Error: vscode code command not found";
        exit 1
    fi

    find_path="/run/user/$UID"
    # List all the vscode-ipc-*.sock files and get the latest one
    new_IPC_HOOK=$(ls -t ${find_path}/vscode-ipc-*.sock | head -1)
    if [[ -z $new_IPC_HOOK ]]
    then
        echo "Error: vscode-ipc-*.sock file not found";
        exit 1
    fi

    # find /run/user/$UID -maxdepth 1 -type s -name "vscode-ipc-*" ! -wholename $new_IPC_HOOK -exec ls {} +
    # Remove vscode-ipc-*.sock files except the latest one
    find /run/user/$UID -maxdepth 1 -type s -name "vscode-ipc-*" ! -wholename $new_IPC_HOOK -delete
    # Remove vscode-git-*.sock files
    find /run/user/$UID -maxdepth 1 -type s -name "vscode-git-*.sock" -delete

    export VSCODE_IPC_HOOK_CLI=$new_IPC_HOOK
    $vscode_code_path $@
}

fcode -g $@