#!/bin/bash
# fcp - Open crash.txt with vim in paste mode and clear content
# Created: April 24, 2025

CRASH_FILE="/data/bugzilla/crash.txt"
[ ! -f "$CRASH_FILE" ] && exit 1

truncate -s 0 "$CRASH_FILE"
vim -c "set paste" "$CRASH_FILE"