#!/bin/bash

file_path="/data/bugzilla/crash.txt"

if [ -f $file_path ]; then
    # Empty the file
    truncate -s 0 "$file_path"
fi

# vim -c "set paste" +"normal! gg" $file_path
vim -c "set paste" $file_path

# check if the content of the file is not empty
if [ -s $file_path ]; then
    # Open the file in vscode after editing
    if command -v code &> /dev/null
    then
        code $file_path:1
    fi
fi
