#!/bin/bash

file_path="/data/bugzilla/crash.txt"

if [ -f $file_path ]; then
    # Empty the file
    truncate -s 0 "$file_path"
else
    touch $file_path
    if [ $? -ne 0 ]; then
        echo "Error: Unable to open file $file_path"
        exit 1
    fi
fi

# Open the file in vim and enter insert mode
vim -c "set paste" -c "startinsert" $file_path

exit 0

# check if the content of the file is not empty
if [ -s $file_path ]; then
    # Open the file in vscode after editing
    if command -v code &> /dev/null
    then
        code $file_path:1
    fi
fi
