#!/bin/bash

gdbLogFile=$(eval echo "$(grep -oP '(?<=set logging file ).*' ~/.gdbinit)")

if [ ! -f "$gdbLogFile" ]; then
    # if not exist, create it
    touch "$gdbLogFile"
fi

if ! command -v bat &> /dev/null
then
    tail -f "$gdbLogFile"
    exit
fi

tail -f "$gdbLogFile" | bat --paging=never -p --color=always -l c
