#!/usr/bin/expect -f

set credentials_file "~/.usr/credentials.txt"

# Check if the file exists
if { ![file exists $credentials_file] } {
    puts "Credentials file not found: $credentials_file."
    set file [open $credentials_file "w"]
    puts $file "Username: Annoymous"
    puts $file "Password: *********"
    close $file
    puts "Credentials file $credentials_file has been created with default content."
    puts "Replace with your credentials and execute again."
    exit 1
}

# Open the credentials file for reading
set file_handle [open $credentials_file r]

# Read the username and password from the file
set ftnt_username ""
set ftnt_password ""
while {[gets $file_handle line] != -1} {
    if {[string match "Username: *" $line]} {
        set ftnt_username [string trimleft $line "Username: "]
    }
    if {[string match "Password: *" $line]} {
        set ftnt_password [string trimleft $line "Password: "]
    }
}

# Remove any newline, carriage return, and space characters from username and password
set ftnt_username [string map {\n "" \r "" " " ""} $ftnt_username]
set ftnt_password [string map {\n "" \r "" " " ""} $ftnt_password]

# Close the credentials file
close $file_handle
