#!/bin/bash

# Recommend to set wad worker count to 1 to make life easier.
# FPX # config system global
# FPX (global) # set wad-worker-count 1
# FPX (global) # end

# SSH Port Forwarding
# -L [bind_address:]port:host:hostport
# -N Do not execute a remote command. This is useful for just forwarding ports.
# Topology:
# Local(127.0.0.1):8881 --- SSH Connect --- Jump Server(172.18.20.226):22 --- Forward Traffic --- Remote(10.40.1.101):22
# Usage:
# $ ssh -N -L Local_IP:Local_Port:Remote_IP:Remote_Port Jump_User@Jump_IP:Jump_Port
# Jump_User@Jump_IP's Passwd:
#
# Give an example:
# $ ssh -N -L 127.0.0.1:8881:10.40.1.101:22 test@172.18.20.226
# test@172.18.20.226's Passwd:
#
# $ netstat -tulnp | grep -i 8881
# tcp        0      0 127.0.0.1:8881          0.0.0.0:*               LISTEN      1208750/ssh
#
# and then
# $ ssh -l admin -p 8881 localhost
# or use
# $ jssh -l admin -P 8881 -t localhost

# Variables
scriptName=$(basename "$0")
fTarget="fgt1"
fWorkerType="worker"
fSSHConnPort=22
fUsername="admin"
fPassword="password"
fPrompt="# "
fGDBServerListenPort=444
fWADWorkerKeep=-1
fWADWorkerCnt=$fWADWorkerKeep # 0: unlimited, 1: 1 worker, -1: keep the original value
fMaxAttempts=2
# Pretty print
USER_NOTATION="@@@@"
SUB_USER_NOTATION="@@@@ @"
separator="----------------------------------------------------------------"

usage() {
    cat << _EOF
$scriptName 0.0.1

Usage: $scriptName [options]
       $scriptName [-t target] [-w worker_type] [-P gdbserver_listen_port] [-T max_attempts]
              [-u/-l username] [-p password] [-P ssh_conn_port] [-h]

Options:
    -t      Target device name or IP address(default: $fTarget)
    -w      Worker type(default: $fWorkerType)
    -d      GDB Server listen port(default: $fGDBServerListenPort)
    -l/-u   Username(default: $fUsername)
    -p      Password(default: $fPassword)
    -P      SSH connection port(default: $fSSHConnPort)
    -N      Set wad worker count(default: $fWADWorkerCnt)
            0: unlimited, 1: 1 worker to make life easier, -1: keep the original value
    -T      Maximum attempt(default: $fMaxAttempts)
    -h      Print this help message

Example:
    $scriptName -t fgt1
    $scriptName -t fgt1 -P 22
    $scriptName -t fgt1 -p "123" -N1
    $scriptName -t fgt1 -w algo -d 9229
    $scriptName -t fgt1 -w algo -d 9229 -l "admin" -p "123"
    $scriptName -h

_EOF
    exit 0
}

[[ $# -eq 0 ]] && usage

# Parse the options
while getopts "t:w:d:T:l:u:p:P:N:h" opt; do
    case $opt in
        t)
            fTarget=$OPTARG
            ;;
        w)
            fWorkerType=$OPTARG
            ;;
        d)
            fGDBServerListenPort=$OPTARG
            ;;
        T)
            fMaxAttempts=$OPTARG
            ;;
        P)
            fSSHConnPort=$OPTARG
            ;;
        l)
            fUsername=$OPTARG
            ;;
        u)
            fUsername=$OPTARG
            ;;
        p)
            fPassword=$OPTARG
            ;;
        N)
            fWADWorkerCnt=$OPTARG
            ;;
        h)
            usage
            ;;
        ?)
            echo "$USER_NOTATION Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

# Shift to process non-option arguments. New $1, $2, ..., $@
shift $((OPTIND - 1))
if [[ $# -gt 0 ]]; then
    echo "$USER_NOTATION Illegal non-option arguments: $@"
    exit
fi

RED='\033[31m'
MAGENTA='\033[35m'
RESET='\033[0m'
COLOR="$RED"

fSearchPatt="type=.*$fWorkerType"
echo $separator
echo -e "$USER_NOTATION [t]Set Target Device to: ${COLOR}$fTarget${RESET}"
echo -e "$USER_NOTATION [w]Set Worker Type to: ${COLOR}$fWorkerType${RESET}(Search Pattern: $fSearchPatt)"
echo -e "$USER_NOTATION [d]Set GDB Server Listen Port to: ${COLOR}$fGDBServerListenPort${RESET}"
echo -e "$USER_NOTATION [P]Set SSH Connection Port to: ${COLOR}$fSSHConnPort${RESET}"
echo -e "$USER_NOTATION [l]Set Username to: ${COLOR}$fUsername${RESET}"
echo -e "$USER_NOTATION [p]Set Password to: ${COLOR}$fPassword${RESET}"
echo -e "$USER_NOTATION [T]Set Maximum Attempts to: ${COLOR}$fMaxAttempts${RESET}"
# if $wadWorkerCnt is larger or equal to 0, then print the message.
if [ "$fWADWorkerCnt" -ge 0 ]; then
    echo -e "$USER_NOTATION [N]Set WAD Worker Count to: ${COLOR}$fWADWorkerCnt${RESET}"
fi
# COLOR="$MAGENTA"
# echo -e "$USER_NOTATION ${COLOR}Connecting to $fTarget${RESET} ..."
echo "$USER_NOTATION Connecting to $fTarget ..."
echo $separator

# expect -d -c "
expect -c "
    # Set your SSH credentials
    set i 1
    set timeout 3
    set has_vdom 0

    # Define ANSI color codes with capitalized names
    # Full list can be found here: http://en.wikipedia.org/wiki/ANSI_escape_code
    # https://stackoverflow.com/questions/12879483/color-texts-at-expect-shell
    set RESET   \"\033\[0m\"
    set BOLD    \"\033\[1m\"
    set RED     \"\033\[31m\"
    set GREEN   \"\033\[32m\"
    set YELLOW  \"\033\[33m\"
    set BLUE    \"\033\[34m\"
    set MAGENTA \"\033\[35m\"
    set CYAN    \"\033\[36m\"
    set WHITE   \"\033\[37m\"

    while {\$i <= $fMaxAttempts} {
        # ssh -o StrictHostKeyChecking=no $fTarget
        if {\$i > 1} {
            send_user \"$USER_NOTATION Login attempt \$i/$fMaxAttempts\n\"
        }
        spawn -noecho ssh -p $fSSHConnPort $fUsername@$fTarget

        set session_id \$spawn_id
        set passwd_prompt_cnt 0
        set COLOR \$RED
        expect {
            {yes/no} {
                send \"yes\r\"
                exp_continue
            }
            -re {[Pp]assword} {
                incr passwd_prompt_cnt
                if {\$passwd_prompt_cnt > 1} {
                    send_user \"\n$USER_NOTATION \${COLOR}Permission denied. Please specify the login credentials.\${RESET}\n\"
                    exit 1
                }
                send \"$fPassword\r\"
                exp_continue
            }
            \"Connection refused\" {
                # send_user \"Connection refused when connecting to $fTarget\n\"
                exit 1
            }
            {Host key verification failed.} {
                send_user \"$USER_NOTATION Host key verification failed. Updating known_hosts file...\n\"
                system \"ssh-keygen -R $fTarget\"
                send_user \"$USER_NOTATION Host key removed from known_hosts file.\n\"
                send_user \"$USER_NOTATION Retrying SSH immediately...\n\"
                # close \$session_id
                incr i
                continue
            }
            # $fPrompt must be quoted.
            \"$fPrompt\" {
                break
            }
            timeout {
                send_user \"$SUB_USER_NOTATION \${COLOR}Timeout when connecting to $fTarget.${RESET}\n\"
                # close \$session_id
                incr i
                continue
            }
            eof {
                send_user \"$SUB_USER_NOTATION \${COLOR}Reached EOF. Program ended.\${RESET}\n\"
                send_user \"$SUB_USER_NOTATION \${COLOR}Please check if $fTarget is a correct device name.\${RESET}\n\"
                exit 1
            }
        }
    }

    if {\$i > $fMaxAttempts} {
        send_user \"$USER_NOTATION Failed to connect to $fTarget\"
        exit 1
    }

    if {$fWADWorkerCnt >= 0} {
        send \"config system global\r\"
        expect {
            {Command fail.} {
                # The device has VDOM
                set has_vdom 1
                expect \"$fPrompt\"
                send \"config global\r\"
                expect \"$fPrompt\"
                send \"config system global\r\"
                exp_continue
            }
            \"$fPrompt\" {
                # Pass through
            }
            timeout {
                send_user \"$USER_NOTATION Timeout when resetting debug.\r\"
                exit 1
            }
        }
        send \"set wad-worker-count $fWADWorkerCnt\r\"
        expect \"$fPrompt\"
        send \"end\r\"
        expect \"$fPrompt\"
        send \"end\r\"
        expect \"$fPrompt\"

        # set wait_time 3
        # send_user \"$USER_NOTATION Wait for \$wait_time seconds to apply the configuration.\n\"
        # for {set j 0} {\$j < \$wait_time * 2} {incr j} {
        #     send_user \"====\"
        # }
        # send_user \"\n\"
        # for {set i 0} {\$i < \$wait_time * 2} {incr i} {
        #     send_user \"====\"
        #     after 500
        # }
        # send \"\r\"
        # expect \"$fPrompt\"

        send \"exit\r\"
        expect eof {
            send_user \"$USER_NOTATION WAD Worker Count has been set to $fWADWorkerCnt.\n\"
            exit 0
        }
    }

    if {\$has_vdom} {
        send \"config global\r\"
        expect \"$fPrompt\"
    }
    send \"diagnose debug disable\r\"
    set timeout 30
    expect {
        {Command fail.} {
            # The device has VDOM
            set COLOR \$MAGENTA
            send_user \"\${COLOR}Warning: The device has VDOM. Switch to the global configuration mode.\${RESET}\n\"
            expect \"$fPrompt\"
            send \"config global\r\"
            exp_continue
        }
        \"$fPrompt\" {
            # Pass through
        }
        timeout {
            send_user \"$USER_NOTATION Timeout when resetting debug.\r\"
            exit 1
        }
    }
    send \"diagnose debug enable\r\"
    expect \"$fPrompt\"
    send \"diagnose test application wad 1000\r\"
    expect \"$fPrompt\"
    set output \$expect_out(buffer)

    # Search for the line with \"type=worker\" and extract the PID
    set worker_pid \"\"
    set worker_cnt 0
    set worker_pids {}

    # Define the pattern to match
    set search_patt $fSearchPatt
    # send_user \"$USER_NOTATION Searching for \$search_patt\n\"

    foreach line [split \$output \"\n\"] {
            if {[regexp -nocase \$search_patt \$line]} {
            # Extract the PID from the line
            set pid_regex {pid=(\d+)}
            if {[regexp \$pid_regex \$line match worker_pid]} {
                # Add the matched PID to the list. lappend: list append.
                lappend worker_pids \$worker_pid
                incr worker_cnt
            }
        }
    }

    if {\$worker_cnt > 1} {
        if {[string match -nocase \"*work*\" $fWorkerType]} {
            set COLOR \$RED
            send_user \"\n$USER_NOTATION \${COLOR}Warning: \$worker_cnt PIDs found: \$worker_pids for WAD process of type $fWorkerType.\${RESET}\n\"
            send_user {$USER_NOTATION Recommend to set wad worker count to 1 to make life easier.
$SUB_USER_NOTATION FPX # config system global
$SUB_USER_NOTATION FPX (global) # set wad-worker-count 1
$SUB_USER_NOTATION FPX (global) # end
$USER_NOTATION Or retry the same command with -N1
            }
        } else {
            send_user \"\n$USER_NOTATION \${COLOR}Warning: \$worker_cnt PIDs found: \$worker_pids for WAD process of type $fWorkerType.\${RESET}\"
            set worker_pid [lindex \$worker_pids 0]
            set COLOR \$GREEN
            send_user \"\n$USER_NOTATION Default to choose the first PID: \${COLOR}\$worker_pid.\${RESET}\n\"
            send_user \"$USER_NOTATION Recommend to check the input worker type.\n\"
        }
    } elseif {\$worker_cnt == 1} {
        set COLOR \$MAGENTA
        send_user \"\n$USER_NOTATION \${COLOR}Exact matched PID: \$worker_pid found for WAD process of type $fWorkerType.\${RESET}\n\"
    } else {
        send_user \"\n$USER_NOTATION \${COLOR}Could not find WAD process of type $fWorkerType.\${RESET}\n\"
        exit 1
    }

    set worker_pid [lindex \$worker_pids 0]

    send \"\r\"
    expect \"$fPrompt\"

    send \"diagnose debug disable\r\"
    set timeout 30
    expect \"$fPrompt\"

    send \"sys sh\r\"
    expect {
        \"Unknown action\" {
            send_user \"$USER_NOTATION No Shell supported. Please check the image version.\n\"
            exit 1
        }
        \"$fPrompt\" {
            # Do nothing, just continue
        }
    }

    # start gdbserver
    set timeout -1
    send \"gdbserver 0.0.0.0:$fGDBServerListenPort --attach \$worker_pid\r\"

    # \x03 is used to send a Ctrl-C signal when the trap detects the SIGINT (Ctrl-C) signal.
    trap {
        # Disable console logging. The output may contain multiple blank lines starts with '/ # '.
        log_user 0
        set COLOR \$RED
        send_user \"\n$USER_NOTATION \${COLOR}CTRL+C captured; sending SIGINT to gdbserver as well.\${RESET}\n\"
        send \x03
        set COLOR \$MAGENTA
        send_user \"$USER_NOTATION \${COLOR}Debugging session terminated.\${RESET}\n\"
    } SIGINT

    # interact
    log_user 1
    expect {
        {Detaching from process} {
            set COLOR \$MAGENTA
            send_user \"$USER_NOTATION \${COLOR}Bye-bye.\${RESET}\n\"
            exit 1
        }
        \"$fPrompt\" {
            # pass through
        }
    }
"

# Process [0]: WAD manager type=manager(0) pid=1014 diagnosis=yes.
# Process [1]: type=worker(2) index=0 pid=18369 state=running
#               diagnosis=no debug=enable valgrind=supported/disabled
# Process [2]: type=algo(3) index=0 pid=1061 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [3]: type=informer(4) index=0 pid=1051 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [4]: type=user-info(5) index=0 pid=1052 state=running
#               diagnosis=no debug=enable valgrind=supported/disabled
# Process [5]: type=dev-vuln(6) index=0 pid=1053 state=running
#               diagnosis=no debug=enable valgrind=supported/disabled
# Process [6]: type=cert-inspection(9) index=0 pid=1054 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [7]: type=YouTube-filter-cache-service(10) index=0 pid=1055 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [8]: type=debug(12) index=0 pid=1056 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [9]: type=config-notify(13) index=0 pid=1057 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [10]: type=tls-fgpt-service(14) index=0 pid=1058 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [11]: type=ia-cache(15) index=0 pid=1059 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
# Process [12]: type=isolator(16) index=0 pid=1060 state=running
#               diagnosis=no debug=enable valgrind=unsupported/disabled
