#!/usr/bin/env bash
# set -x

fortidevSymlink="/fortidev"
fortidev6="$HOME/.cache/fortinet/fortidev/fortidev-6.0.2"
fortidev7="$HOME/.cache/fortinet/fortidev/fortidev-7.0.0"
fortidev=$(readlink $fortidevSymlink)
targetFortidev=""

usage() {
    cat << _EOF
This script changes the symlink to fortidev between version 6 and 7

Usage: $(basename "$0") [-7|-6]
  -7: Switch to $(basename "$fortidev7")
  -6: Switch to $(basename "$fortidev6")

Current symlink points to: $fortidev

_EOF
    exit 1
}

while getopts "f67h" opt; do
    case "$opt" in
        6)
            targetFortidev="$fortidev6"
            ;;
        7)
            targetFortidev="$fortidev7"
            ;;
        h)
            usage
            ;;
        *)
            usage
            ;;
    esac
done
shift "$((OPTIND-1))"

if [[ -n "$targetFortidev" ]]; then
    if [[ ! -d "$targetFortidev" ]]; then
        echo "Error: $targetFortidev not found"
        exit 1
    fi
    if [[ "$fortidev" == "$targetFortidev" ]]; then
        echo "Already using $(basename "$targetFortidev"). No change needed."
    else
        echo "Switching to $(basename "$targetFortidev")"
        cd /
        sudo rm -rf fortidev
        sudo ln -s "$targetFortidev" fortidev
    fi
fi

ls -l "$fortidevSymlink"
