#!/bin/bash

if ! command -v get_credentials &> /dev/null; then
    echo "Error: Command get_credentials not found."
    exit 1
fi

if ! credentials_output=$(eval get_credentials); then
    echo "Error: Failed to get credentials."
    exit 1
fi

mapfile -t credentials <<< "$credentials_output"
ftntUser=${credentials[0]}
ftntPasswd=${credentials[1]}

USER_NOTATION="@@@@"
SCRIPT_LOCATION="/tmp/git_fetch_repos"

# check if the script exists
if [ ! -f "$SCRIPT_LOCATION" ]; then
    cat << _EOF > $SCRIPT_LOCATION
#!/bin/bash
# set -x

repos=(
    "/data/fos"
    "/data/fos2"
    "/data/fpx"
    "/data/fpx2"
    "/data/sandbox/fos_repro"
    "/data/sandbox/fpx_repro"
    "/data/sandbox/fortios-ci"
)

update_git_repo() {
    local repo_path="\$1"

    echo -e  "\n$USER_NOTATION Updating repository: \$repo_path"

    # Change to the repository directory
    cd "\$repo_path" || exit 1

    # Check if it's a Git repository
    if [ -d ".git" ]; then
        echo "$USER_NOTATION Fetching tags:"
        git fetch --tags
        # Check if fetching was successful
        if [ $? -ne 0 ]; then
            echo "$USER_NOTATION Error fetching tags. Aborting."
            exit 1
        fi
        echo "$USER_NOTATION Fetching branches: main"
        git fetch origin main
        echo "$USER_NOTATION Fetching branches: 7.0"
        git fetch origin 7.0
        echo "$USER_NOTATION Fetching branches: 7.2"
        git fetch origin 7.2
        # FPX does not have 7.4 branch currently. Mar.11 2024
        # git ls-remote --exit-code --quiet --heads origin 7.4
        git ls-remote --exit-code --quiet --heads origin 7.4
        if [ $? -eq 0 ]; then
            git fetch origin 7.4
        fi
    else
        echo "$USER_NOTATION Not a Git repository: \$repo_path"
    fi

    # Return to the original directory
    cd - &>/dev/null
}

for repo in "\${repos[@]}"; do
    update_git_repo "\$repo"
done

if [ ! -x "$SCRIPT_LOCATION" ]; then
    chmod +x $SCRIPT_LOCATION
fi
_EOF
fi

expect -c "
    proc common_expect_block {fa_pattern} {
        global pattern_found user_notation
        expect {
            {yes/no} {
                send \"yes\r\"
                exp_continue
            }
            -re {[Uu]sername} {
                send \"$ftntUser\r\"
                exp_continue
            }
            -re {[Pp]assword} {
                send \"$ftntPasswd\r\"
                exp_continue
            }
            -re \$fa_pattern {
                puts \"$USER_NOTATION Pattern \$fa_pattern\ Found in the output.\"
                set pattern_found true
            }
            {OTP: } {
                # Promption for reading the FortiToken from the user
                expect_user -re \"(.*)\n\"
                set token \$expect_out(1,string)
                send \"\$token\r\"
                exp_continue
            }
            timeout {
                puts \"$USER_NOTATION Timed out! Have you set up your VPN?\"
                exit 1
            }
            eof {}
        }
    }

    set fa_pattern \"2fa_verify\"
    set pattern_found false
    set timeout -1
    spawn bash $SCRIPT_LOCATION
    # exp_internal 1
    common_expect_block \$fa_pattern
    if {\$pattern_found == false} {
        exit 1
    }

    set fa_pattern \"OTP validation failed:\"
    set pattern_found false
    set timeout 180
    spawn ssh git@git-van.corp.fortinet.com 2fa_verify
    common_expect_block \$fa_pattern
    if {\$pattern_found == true} {
        exit 1
    }

    set timeout -1
    spawn bash $SCRIPT_LOCATION

    expect eof
"
