#!/bin/bash
# set -x

# Build flags & Options
ftntUser=""
ftntPasswd=""
fPlatform="FOS" # Default platform
ftntBuildTarget="image.out"
fBuildTarget="$ftntBuildTarget"
fBuildModel=""
fNumOfJobs=$(nproc)
fWorkingDir=$(pwd)
fMaxBuildAttempt=1
fUseBear=false
fRunConfigure=false
fNeedBuild=false
fPrintBuildFlags=false # Print build flags
fGitClean=false
fRMCompileCommandsJson=false
# Sync Options
fSyncTarget=false
fSyncFile=$fBuildTarget
fSyncPort=22
fSyncUsername="admin"
fSyncPassword="password"
# Git associated variables
compileCommandsFile="compile_commands.json"
gitExcludePattern1=$compileCommandsFile
gitExcludePattern2="\*.code-workspace"
gitExcludeList="$gitExcludePattern1 $gitExcludePattern2"
# Common Constants
SCRIPT_NAME=$(basename $0)
USER_NOTATION="@@@@"
# SHORT_SEPARATOR="--------------"
# SEPARATOR="---------------------------------------------------"
# SHORT_SEPARATOR2="=============="
SEPARATOR2="==================================================="
# Colors
CYAN='\033[36m'
RED='\033[31m'
BOLD='\033[1m'
GREEN='\033[32m'
MAGENTA='\033[35m'
BLUE='\033[34m'
GREY='\033[90m'
LIGHTYELLOW='\033[93m'
# YELLOW='\033[33m'
RESET='\033[0m'

getCurrentTime() {
    COLOR="$RED"
    echo -e "${COLOR}$(date +"%m/%d/%Y %H:%M:%S")${RESET}"
}

# https://patorjk.com/software/taag/
showLogo() {
    cat << _EOF
      _              __          ___ ____ ___   ___
     (_)__ _  ___ _ / /__ ___   <  // __/( _ ) ( _ )
    / //  ' \/ _  //  '_// -_)  / // _ \/ _  |/ _  |
 __/ //_/_/_/\_,_//_/\_\ \__/  /_/ \___/\___/ \___/
|___/
_EOF
}

usage() {
    cat << _EOF
Usage: $SCRIPT_NAME [options]
       $SCRIPT_NAME [-m model] [-w working_dir] [-j num_of_jobs] [-T max_attempt]
             [-s sync_target] [-S sync_file] [-P sync_port] [-l/-u username] [-p password]
             [-B build_target]
             [-bcCohf]

Build Flags:
    -c      Clean the repo (default: $fGitClean)
    -C      Run Configure intelligently (default: $fRunConfigure)
    -o      Run build commands (set automatically if any of the [bmjwT] options is set)
    -b      Use Bear to generate $compileCommandsFile (default: $fUseBear)
    -f      Remove $compileCommandsFile (default: $fRMCompileCommandsJson)
Build Options:
    -T      Set the maximum number of build attempts (default: $fMaxBuildAttempt)
    -B      Set the build target (default: $fBuildTarget)
    -m      Set the build model  (default: $fBuildModel)
    -j      Set the number of jobs (default: $fNumOfJobs)
    -w      Set working directory  (default: $fWorkingDir)
Sync Options:
    -s      Set the sync source file (default: $fSyncFile)
    -t      Set the sync target machine (default: $fSyncTarget)
    -P      Set the sync ssh port (default: $fSyncPort)
    -l/-u   Set the sync username (default: $fSyncUsername)
    -p      Set the sync password (default: $fSyncPassword)
Other Options:
    -h      Print this help message

Example:
    $SCRIPT_NAME -m FGT_VM64_KVM -c -T1 -j4 -b
    $SCRIPT_NAME -m vmware
    $SCRIPT_NAME -t fgt1 -s FGT_VM64_KVM-v7-build1662.out -u "admin" -p "password" -P 22
    $SCRIPT_NAME -h

_EOF
    exit 0
}

[[ $# -eq 0 ]] && usage

# Parse the options
while getopts "hm:w:j:cCbB:ofT:t:s:P:p:u:l:" opt; do
    case $opt in
        m)
            fBuildModel=$OPTARG
            fNeedBuild=true
            ;;
        w)
            fWorkingDir=$OPTARG
            fNeedBuild=true
            ;;
        j)
            fNumOfJobs=$OPTARG
            fNeedBuild=true
            ;;
        T)
            fMaxBuildAttempt=$OPTARG
            fNeedBuild=true
            ;;
        b)
            fUseBear=true
            fRMCompileCommandsJson=true
            fNeedBuild=true
            ;;
        B)
            fBuildTarget=$OPTARG
            fNeedBuild=true
            ;;
        C)
            fRunConfigure=true
            ;;
        c)
            # Ignore compile_commands.json by default
            fGitClean=true
            ;;
        f)
            fRMCompileCommandsJson=true
            ;;
        t)
            fSyncTarget=$OPTARG
            ;;
        s)
            fSyncFile=$OPTARG
            ;;
        P)
            fSyncPort=$OPTARG
            ;;
        l)
            fSyncUsername=$OPTARG
            ;;
        u)
            fSyncUsername=$OPTARG
            ;;
        p)
            fSyncPassword=$OPTARG
            ;;
        o)
            fNeedBuild=true
            ;;
        h)
            usage
            ;;
        ?)
            echo -e "$USER_NOTATION ${MAGENTA}Invalid option: $OPTARG${RESET}"
            exit 1
            ;;
    esac
done

# Shift to process non-option arguments. New $1, $2, ..., $@
shift $((OPTIND - 1))
if [[ $# -gt 0 ]]; then
    echo "$USER_NOTATION Illegal non-option arguments: $@"
    exit
fi

# $1: available models, $2: target model
searchModel() {
    matchedModels=()
    local availModels="$1"
    local targetModel="$2"
    for model in $availModels; do
        if [[ "$model" == *"$targetModel"* ]]; then
            matchedModels+=("$model")
        fi
    done

    COLOR="$RED"
    case ${#matchedModels[@]} in
        0)
            echo -e "$USER_NOTATION No matched model found for ${COLOR}$targetModel${RESET}"
            exit 1
            ;;
        1)
            fBuildModel="${matchedModels[0]}"
            ;;
        *)
            echo "$USER_NOTATION Multiple matched models found for $targetModel"
            echo "$USER_NOTATION Please specify the model from the following list:"
            for model in "${matchedModels[@]}"; do
                echo -e "$USER_NOTATION ${COLOR}$model${RESET}"
            done
            exit 1
            ;;
    esac
}

preParseOptions() {
    # Set fRunConfigure to true if fNeedBuild is true
    [[ "$fNeedBuild" == true ]] && fRunConfigure=true

    [[ "$fGitClean" == true || "$fRunConfigure" == true || "$fNeedBuild" == true
     || "$fUseBear" == true || "$fRMCompileCommandsJson" == true ]] && fPrintBuildFlags=true

    [[ "$fPrintBuildFlags" == false ]] && return

    command -v realpath >/dev/null 2>&1 && fWorkingDir=$(realpath "$fWorkingDir")
    if [[ ! -d "$fWorkingDir" ]]; then
        echo "$USER_NOTATION Directory $fWorkingDir not found"
        exit 1
    fi

    cd "$fWorkingDir" || exit
    if [[ ! -x "$(command -v ./Configure)" ]]; then
        echo "$USER_NOTATION Command Configure not found in $fWorkingDir"
        exit 1
    fi
    availModels="$(./Configure list)"
    for model in $availModels; do
        if [[ "$model" == "FPX"* ]]; then
            fPlatform="FPX"
            break
        fi
    done

    # Upper case the build model
    fBuildModel=$(echo "$fBuildModel" | tr '[:lower:]' '[:upper:]')

    if [[ "$fPlatform" == "FPX" ]]; then
        if [[ "$fBuildModel" == "" ]]; then
            fBuildModel="FPX_KVM"
        else
            # Change the max build attempt to 2 for FPX
            fMaxBuildAttempt=2
            searchModel "$availModels" "$fBuildModel"
        fi
    else
        # The platform is FOS
        if [[ "$fBuildModel" == "" ]]; then
            fBuildModel="FGT_VM64_KVM"
        elif [[ "$fBuildModel" == "VMWARE" ]]; then
            fBuildModel="FGT_VM64"
        else
            searchModel "$availModels" "$fBuildModel"
        fi
    fi
}

preParseOptions
# exit 0 # Just for debugging

showLogo

echo $SEPARATOR2
if [[ "$fPrintBuildFlags" != false ]]; then
    COLOR="$GREEN"
    # echo "$SEPARATOR"
    echo -e "${BOLD}Build Flags:${RESET}"
    # echo "$SHORT_SEPARATOR"
    [[ "$fGitClean"     == true ]] && echo -e "$USER_NOTATION [c] ${COLOR}Clean${RESET} the repo"
    [[ "$fRunConfigure" == true ]] && echo -e "$USER_NOTATION [C] ${COLOR}Configure${RESET} the project"
    [[ "$fNeedBuild"    == true ]] && echo -e "$USER_NOTATION [o] ${COLOR}Build${RESET} the project"
    [[ "$fUseBear"      == true ]] && echo -e "$USER_NOTATION [b] ${COLOR}Generate${RESET} compile_commands.json using bear"
    [[ "$fRMCompileCommandsJson" == true ]] && echo -e "$USER_NOTATION [f] ${COLOR}Remove${RESET} the existing $compileCommandsFile"
fi

if [[ "$fNeedBuild" != false ]]; then
    # echo "$SEPARATOR"
    echo -e "${BOLD}Build Optioins:${RESET}"
    # echo "$SHORT_SEPARATOR"
    COLOR="$RED"
    echo -e "$USER_NOTATION [m] Build Modle:  ${COLOR}$fBuildModel${RESET}"
    COLOR="$CYAN"
    echo -e "$USER_NOTATION [B] Build Target: ${COLOR}$fBuildTarget${RESET}"
    echo -e "$USER_NOTATION [w] Working Directory: ${COLOR}$fWorkingDir${RESET}"
    echo -e "$USER_NOTATION [T] Maximum Build Attempts: ${COLOR}$fMaxBuildAttempt${RESET}"
    echo -e "$USER_NOTATION [j] Concurrent Build Jobs:  ${COLOR}$fNumOfJobs${RESET}"
fi

if [[ "$fSyncTarget" != false ]]; then
    COLOR="$RED"
    # echo "$SEPARATOR"
    echo -e "${BOLD}Sync Optioins:${RESET}"
    # echo "$SHORT_SEPARATOR"
    echo -e "$USER_NOTATION [s] Scheduled to sync ${COLOR}$fSyncFile${RESET} to ${COLOR}$fSyncTarget${RESET}"
    echo -e "$USER_NOTATION [l] User:     (${COLOR}$fSyncUsername${RESET})"
    echo -e "$USER_NOTATION [p] Password: (${COLOR}$fSyncPassword${RESET})"
    echo -e "$USER_NOTATION [S] Sync File:   (${COLOR}$fSyncFile${RESET})"
    echo -e "$USER_NOTATION [S] Sync Target: (${COLOR}$fSyncTarget${RESET})"
fi
echo "$SEPARATOR2"
# sleep 0.1

# Clean the working directory
if [[ "$fGitClean" == true ]]; then
    echo "$USER_NOTATION Cleaning the working directory ..."

    COLOR="$MAGENTA"
    cd "$fWorkingDir" || exit
    gitExcludePattern=""
    for patt in $gitExcludeList; do
        if [[ "$fRMCompileCommandsJson" == true ]]; then
            if [[ "$patt" == "$compileCommandsFile" ]]; then
                # Do not add it to the exclude list
                echo -e "$USER_NOTATION ${COLOR}Remove $compileCommandsFile${RESET}"
                continue
            fi
        fi
        echo -e "$USER_NOTATION Exclude ${COLOR}$patt${RESET}"
        gitExcludePattern+="--exclude=$patt "
    done

    COLOR="$BLUE"
    gitCleanCmd="git clean -xdf $gitExcludePattern"
    echo -e "$USER_NOTATION Running: ${COLOR}$gitCleanCmd${RESET}"

    sleep 1
    COLOR="$RED"
    eval "$gitCleanCmd"
    if [[ $? -ne 0 ]]; then
        echo -e "$USER_NOTATION ${COLOR}Failed to clean the working directory.${RESET}"
        exit 1
    else
        echo -e "$USER_NOTATION ${COLOR}Cleaned the working directory successfully.${RESET}"
    fi
fi

expectPath=$(command -v expect)
if [[ -z "$expectPath" ]]; then
    echo "$USER_NOTATION Command expect not found"
    exit 1
fi

# Step 1: Run Configure
if [[ "$fRunConfigure" == true ]]; then
    if ! command -v get_credentials &> /dev/null; then
        echo -e "$USER_NOTATION ${RED}Error: Command get_credentials not found.${RESET}"
        exit 1
    fi

    if ! credentials_output=$(eval get_credentials); then
        echo -e "$USER_NOTATION ${RED}Error: Failed to get credentials.${RESET}"
        exit 1
    fi

    mapfile -t credentials <<< "$credentials_output"
    ftntUser=${credentials[0]}
    ftntPasswd=${credentials[1]}

    COLOR=$BLUE
    CONFIGURE_CMD="./Configure -m $fBuildModel -d y -c"
    echo -e "$USER_NOTATION Running Configure: ${COLOR}$CONFIGURE_CMD${RESET}"
    COLOR=$MAGENTA
    echo -e "$USER_NOTATION ${COLOR}Spawning a new bash session.${RESET}"
    sleep 1

    # expect -d -c "
    expect -c "
        set config_bash_prompt \"$ \"

        log_user 1
        # exp_internal 1
        spawn -noecho bash

        expect \"\$config_bash_prompt\"
        send \"cd $fWorkingDir\r\"
        expect \"\$config_bash_prompt\"
        send \"$CONFIGURE_CMD\r\"

        set timeout 180
        expect {
            {Username} {
                send \"$ftntUser\r\"
                exp_continue
            }
            {Password for '$ftntUser':} {
                send \"$ftntPasswd\r\"
                exp_continue
            }
            \"\$config_bash_prompt\" {
                # log_user 0
                # send \"exit\r\"
                send \"\x04\r\"
            }
            timeout {
                puts stderr \"$USER_NOTATION Timeout. Action aborted.\n\"
                exit 1
            }
        }
    "

    COLOR=$MAGENTA
    if [[ $? -ne 0 ]]; then
        echo -e "$USER_NOTATION ${COLOR}Failed to run Configure.${RESET}"
        exit 1
    else
        echo -e "$USER_NOTATION ${COLOR}Configure completed successfully.${RESET}"
    fi
fi

# Step 2: Run build commands
if [[ "$fNeedBuild" != false ]]; then
    # Make make command
    cd "$fWorkingDir" || exit
    makeCommand="make -j$fNumOfJobs $fBuildTarget"

    # Use Bear to generate compile_commands.json
    if [[ "$fUseBear" == true ]]; then
        bearPath=$(command -v bear)
        if [[ -z "$bearPath" ]]; then
            echo "$USER_NOTATION Command bear not found, please install it first"
            echo "$USER_NOTATION sudo apt install bear libear -y"
            exit 1
        fi
        pathOfLibear=$(locate libear.so | grep -m 1 libear.so)
        if [[ "$pathOfLibear" != "" ]]; then
            bear="bear -l $pathOfLibear"
        else
            defaultLiBearPath="/usr/lib/x86_64-linux-gnu/bear/libear.so"
            if [[ ! -f "$defaultLiBearPath" ]]; then
                echo "$USER_NOTATION libear.so not found, please install it first"
                echo "$USER_NOTATION sudo apt install libear -y"
                exit 1
            fi
            bear="bear -l $defaultLiBearPath"
        fi
        makeCommand="$bear $makeCommand"
    fi

    # Loop to build the projects
    attempt=1
    maxAttempt=$fMaxBuildAttempt
    while [[ $attempt -le $maxAttempt ]]; do
        COLOR="$GREEN"
        echo -e "$USER_NOTATION Running build commands: ${COLOR}$makeCommand${RESET}"
        echo -e "$USER_NOTATION ${COLOR}Build attempt $attempt/$maxAttempt${RESET}"
        # [[ $attempt -gt 1 ]] && sleep 2
        sleep 2

        eval "$makeCommand"
        eval_status=$?
        if [[ $eval_status -eq 0 ]]; then
            break
        else
            attempt=$((attempt + 1))
        fi
    done

    if [[ $eval_status -ne 0 ]]; then
        COLOR="$RED"
        echo "$USER_NOTATION Build projects failed."
        echo -e "$USER_NOTATION ${COLOR}Suggest to clean the working directory and try again.${RESET}"
        exit 1
    fi

    # Remove the write privilege of compile_commands.json if it is writable
    jsonFile=$compileCommandsFile
    jsonPath=$fWorkingDir/$jsonFile
    COLOR=$MAGENTA
    if [[ -f "$jsonPath" ]]; then
        if [[ -w "$jsonPath" ]]; then
            echo -e "$USER_NOTATION ${COLOR}$jsonPath is writable${RESET}"
            echo -e "$USER_NOTATION ${COLOR}Remove the write privilege of $jsonPath${RESET}"
            chmod -w "$jsonPath"
            if [[ $? -ne 0 ]]; then
                echo -e "$USER_NOTATION ${COLOR}Failed to remove the write privilege of $jsonPath${RESET}"
                exit 1
            fi
        else
            echo -e "$USER_NOTATION ${COLOR}$jsonPath is read-only${RESET}"
        fi
    else
        echo -e "$USER_NOTATION ${COLOR}No $jsonFile found in $fWorkingDir${RESET}"
        if [[ "$fUseBear" == true ]]; then
            echo -e "$USER_NOTATION ${COLOR}Please check the bear command${RESET}"
            exit 1
        fi
    fi

    echo "$USER_NOTATION Congratulations! You have built projects successfully at $(getCurrentTime)"
fi

# Step 3: Sync the SYNC_FILE to the target machine
if [[ "$fSyncTarget" != false ]]; then
    # The -t option tells mapfile to strip the trailing newlines from each line it reads.
    mapfile -t syncFiles < <(find "$fWorkingDir" -name "$fSyncFile")
    if [[ ${#syncFiles[@]} -eq 0 ]]; then
        echo "$USER_NOTATION $fSyncFile not found in $fWorkingDir"
        exit 1
    fi

    # Only sync the first file that is found.
    syncFile="${syncFiles[0]}"
    COLOR="$BLUE"
    echo -e "$USER_NOTATION Syncing ${COLOR}$syncFile${RESET} to ${COLOR}$fSyncTarget${RESET} ..."

    maxSyncRetries=3
    ESUCCESS=0
    EMAXTRIES=$(($maxSyncRetries + 1))
    ETIMEOUT=$(($maxSyncRetries + 10))
    EFAILED=$((ETIMEOUT + 1))
    # If not use escape for $i, it will be replaced by the value of $i, since it is in the bash environment.
    # But \$i will keep as $i in the expect script generated.
    # expect -d -c "
    expect -c "
        # Set the initial values
        set defaultTimeout 600
        set adjustTimeout 0
        set waitBeforeRetry 10
        set passwd_prompt_cnt 0

        # Loop to sync the file
        for {set i 1} {\$i <= $maxSyncRetries} {incr i} {
            puts stderr \"$USER_NOTATION Sync attempt \$i/$maxSyncRetries\"
            spawn -noecho scp -P $fSyncPort $syncFile ${fSyncUsername}@${fSyncTarget}:/fgt-image
            if {\$adjustTimeout != 0} {
                set timeout \$adjustTimeout
            } else {
                set timeout \$defaultTimeout
            }

            expect {
                \"bad port\" {
                    puts stderr \"$USER_NOTATION Bad port. Connecting aborted.\"
                    exit $EFAILED
                }
                {yes/no} {
                    send \"yes\r\"
                    exp_continue
                }
                -nocase {Password:} {
                    incr passwd_prompt_cnt
                    if {\$passwd_prompt_cnt > 1} {
                        puts stderr \"\n$USER_NOTATION Permission Denied. Please specify the login credentials.\"
                        exit $EFAILED
                    }
                    send \"$fSyncPassword\r\"
                    exp_continue
                }
                \"Host key verification failed.\" {
                    puts stderr \"$USER_NOTATION Host key verification failed. Updating known_hosts file...\"
                    puts stderr \"$USER_NOTATION Executing: ssh-keygen -R $fSyncTarget\"
                    system \"ssh-keygen -R $fSyncTarget\"
                    puts stderr \"$USER_NOTATION Host key removed from known_hosts file.\"
                    puts stderr \"$USER_NOTATION Retrying SCP immediately...\"
                    continue
                }
                -re {Connection refused|No route to host} {
                    set adjustTimeout -1
                    puts stderr \"$USER_NOTATION Waiting for \$waitBeforeRetry seconds before retrying ...\"
                    sleep \$waitBeforeRetry
                    # Exponential backoff
                    set waitBeforeRetry [expr {\$waitBeforeRetry * 2}]
                    continue
                }
                \"501-Permission Denied\" {
                    puts stderr \"$USER_NOTATION Permission Denied. Please enable admin-scp under 'config system global'.\"
                    exit $EFAILED
                }
                \"check image error\" {
                    puts stderr \"$USER_NOTATION Check image error. Action aborted.\"
                    # exp_continue
                    exit $EFAILED
                }
                \"100-update image completed\" {
                    puts stderr \"$USER_NOTATION 100-update image completed. Action completed.\"
                    exit $ESUCCESS
                }
                \"lost connection\" {
                    puts stderr \"$USER_NOTATION Lost connection. Action aborted.\"
                    exit $EFAILED
                }
                timeout {
                    puts stderr \"$USER_NOTATION Timeout. Action aborted.\"
                    exit $ETIMEOUT
                }
                eof {
                    puts stderr \"$USER_NOTATION Reaching EOF.\"
                    exit $ESUCCESS
                }
            }
        }
        exit \$i
    "

    retValue=$?
    [[ $retValue -ne 0 ]] && echo "$USER_NOTATION Sync return value: $retValue"

    case $retValue in
        $ESUCCESS)
            COLOR=$GREY
            echo -e "$USER_NOTATION You have synced $fSyncFile to $fSyncTarget successfully at $(getCurrentTime)"
            echo -e "$USER_NOTATION ${COLOR}Login to the server and wait for it to reboot${RESET} ..."
            jssh -P "$fSyncPort" -u "$fSyncUsername" -p "$fSyncPassword" -t "$fSyncTarget"
            if [[ $? -ne 0 ]]; then
                echo "$USER_NOTATION Please check the server status manually."
                exit 1
            else
                echo -e "$USER_NOTATION Target ${MAGENTA}$fSyncTarget${RESET} started to reboot at $(getCurrentTime)"
                exit 0
            fi
            ;;
        $EMAXTRIES)
            echo "$USER_NOTATION Failed to sync $fSyncFile to $fSyncTarget after $maxSyncRetries attempts"
            exit $EMAXTRIES
            ;;
        $ETIMEOUT)
            echo "$USER_NOTATION Timeout to sync $fSyncFile to $fSyncTarget"
            exit $ETIMEOUT
            ;;
        *)
            echo "$USER_NOTATION Failed to sync $fSyncFile to $fSyncTarget"
            exit $EFAILED
            ;;
    esac
fi
