#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: frg <search term>"
    exit 1
fi

query="$@"
query_removed_escapes=$(echo "$query" | sed 's/\\//g')
result=$(rg --smart-case \
            --color=ansi \
            --colors 'match:fg:204,51,153' --colors 'match:style:bold' \
            --line-number --no-heading "$query" |
        fzf --ansi \
            --color 'hl:-1:underline,hl+:-1:underline:reverse' \
            --delimiter ':' \
            --preview "bat --color=always {1} --theme='TwoDark' --highlight-line {2}" \
            --preview-window 'top,60%,border-bottom,+{2}+3/3,~3' \
            --cycle \
            --query "$query_removed_escapes")

if [ -z "$result" ]; then
    exit 1
fi

file="${result%%:*}"
linenumber=$(echo "${result}" | cut -d: -f2)

EDITOR="vim"
if [ ! -z "$file" ]; then
    if [ -x "$(command -v code)" ]; then
        EDITOR="code"
        $EDITOR "$file":"$linenumber"
    else
        $EDITOR +"${linenumber}" "$file"
    fi
fi
