#!/bin/bash

# SSH Local Forwarding
# -L [bind_address:]port:host:hostport
# -N Do not execute a remote command. This is useful for just forwarding ports.
# Topology:
# Local(127.0.0.1:8881) -> Jump server(172.18.20.226:22) -> Remote(10.40.1.101:22)
# $ ssh -N -L 127.0.0.1:8881:10.40.1.101:22 test@172.18.20.226
# test@172.18.20.226's fPasswd:
#
# $ netstat -tulnp | grep -i 8881
# tcp        0      0 127.0.0.1:8881          0.0.0.0:*               LISTEN      1208750/ssh
#
# and then
# $ ssh -l admin -p 8881 localhost
# or use
# $ jssh -l admin -P 8881 -t localhost

# Variables
scriptName=$(basename $0)
fSSHPort=22
fLoginUser="admin"
fPasswd="password"
fExpectRoot="# "
fExpectUser="$ "
fExpect=$fExpectUser
fTarget="fgt1"
fMaxAttempts=2
# Print Pretty
userNotation="@@@@"
separator="----------------------------------------------------------------"

usage() {
cat << _EOF
jssh 0.1

usage:
    $scriptName [-l user] [-p passwd] [-P ssh_port] [-E expect] -t target_ip

Options:
    -P fSSHPort        SSH port to use. Default is "$fSSHPort"
    -l fLoginUser      User to use for login. Default is "$fLoginUser"
    -u fLoginUser      User to use for login. Default is "$fLoginUser"
    -p fPasswd         Password to use for login. Default is "$fPasswd"
    -E fExpect         Except prompt to expect(other than "$fExpectRoot"). Default is "$fExpectUser".
    -t fTarget(IP)     The device to connect to. Default is "$fTarget"

Example:
    $scriptName -t fpx1
    $scriptName -l admin -p 123 -t fgt1 -p 22
    $scriptName -l admin -p 123 -t 172.16.67.181

_EOF
    exit 0
}

[[ $# -eq 0 ]] && usage

# Parse command-line options
while getopts "p:l:u:t:P:E:h" opt; do
    case ${opt} in
        p)
            fPasswd=$OPTARG
            ;;
        u) # User
            fLoginUser=$OPTARG
            ;;
        l) # User
            fLoginUser=$OPTARG
            ;;
        t)
            fTarget=$OPTARG
            ;;
        E)
            fExpect=$OPTARG
            ;;
        P)
            fSSHPort=$OPTARG
            ;;
        h)
            usage
            ;;
        ?)
            echo "$userNotation Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

# Shift to process non-option arguments. New $1, $2, ..., $@
shift $((OPTIND - 1))
if [[ $# -gt 0 ]]; then
    echo "$userNotation Illegal non-option arguments: $@"
    exit
fi

echo $separator
echo "$userNotation Set Target Device to: $fTarget"
echo "$userNotation Set SSH Connection Port to: $fSSHPort"
echo "$userNotation Set Username to: $fLoginUser"
echo "$userNotation Set Password to: $fPasswd"
echo "$userNotation Set Maximum Attempts to: $fMaxAttempts"
echo "$userNotation Connecting to $fTarget..."
echo $separator

# expect -d -c "
expect -c "
    set timeout 5
    for {set i 1} {\$i <= $fMaxAttempts} {incr i} {
        # ssh -o StrictHostKeyChecking=no $fTarget
        # send_user \"Sync attempt \$i/$fMaxAttempts\n\"
        spawn -noecho ssh -p $fSSHPort $fLoginUser@$fTarget

        set process_id \$spawn_id
        set passwd_prompt_cnt 0
        expect {
            {yes/no} {
                send \"yes\r\"
                exp_continue
            }
            -re {[Pp]assword} {
                incr passwd_prompt_cnt
                if {\$passwd_prompt_cnt > 1} {
                    send_user \"\n$userNotation Permission denied. Have you specified the login credentials?\n\"
                    exit 1
                }
                send \"$fPasswd\r\"
                exp_continue
            }
            {Host key verification failed.} {
                send_user \"$userNotation Host key verification failed. Updating known_hosts file...\n\"
                system \"ssh-keygen -R $fTarget\"
                send_user \"$userNotation Host key removed from known_hosts file.\n\"
                send_user \"$userNotation Retrying SSH immediately...\n\"
                continue
            }
            \"$fExpectRoot\" {
                break
            }
            \"$fExpect\" {
                break
            }
            timeout {
                send_user \"$userNotation Timed out waiting for a response.\n\"
                close \$process_id
                incr i
                continue
            }
            eof {
                send_user \"$userNotation Reached EOF. Program ended.\n\"
                exit 1
            }
        }
    }

    if {\$i == $fMaxAttempts} {
        send_user \"$userNotation Failed to connect to $fTarget\"
        exit 1
    }

    send_user \"$userNotation Successfully connected to $fTarget.\"
    send \"\r\"
    # Interact with the device
    interact
"

# + expect -d -c '
#     for {set i 1} {$i <= 2} {incr i} {
#         # ssh -o StrictHostKeyChecking=no 172.18.20.230
#         # send_user "Sync attempt $i/2\n"
#         spawn -noecho ssh admin@172.18.20.230

#         expect {
#             {yes/no} {
#                 send "yes\r"
#                 exp_continue
#             }
#             -re {[Pp]assword} {
#                 send "\r"
#                 exp_continue
#             }
#             "Host key verification failed." {
#                 send_user "@@@@ Host key verification failed. Updating known_hosts file...\n"
#                 system "ssh-keygen -R 172.18.20.230"
#                 send_user "@@@@ Host key removed from known_hosts file.\n"
#                 send_user "@@@@ Retrying SSH immediately...\n"
#                 continue
#             }
#             "Connection refused" {
#                 send_user "@@@@ Connection refused. Exiting...\n"
#                 exit 1
#             }
#             eof {
#                 puts "Reached EOF. Exiting..."
#                 exit 1
#             }
#             timeout {
#                 puts "Timed out waiting for a response."
#                 exit 1
#             }
#             "# " {
#                 puts "@@@@ Successfully connected to 172.18.20.230"
#                 break
#             }
#         }
#     }

#     send "\r"
#     expect "# "

#     # Now you can add additional commands or interactions as needed
#     # For example, you can automate further commands here

#     # Interact with the device
#     interact
# '
