#!/bin/bash

# Set the header for the Expect script
SCRIPT_NAME=$(basename $0)

usage() {
    echo "Usage: $SCRIPT_NAME IP_ADDRESS"
    exit 1
}

while getopts "h" opt; do
    case $opt in
        h)
            usage
            ;;
        ?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

if [ -z "$1" ]; then
    echo "Error: IP address is required."
    usage
fi
target=$1

if ! command -v get_credentials &> /dev/null; then
    echo "Error: Command get_credentials not found."
    exit 1
fi

if ! credentials_output=$(get_credentials); then
    echo "Error: Failed to get credentials."
    exit 1
fi

mapfile -t credentials <<< "$credentials_output"
ftnt_username=${credentials[0]}
ftnt_password=${credentials[1]}

spawnCmd="telnet $target"
echo "Spawned command: $spawnCmd"

expect -c "
    set timeout 25
 
    spawn -noecho $spawnCmd
    # exp_internal 1
    expect {
        {login: } {
            send \"$ftnt_username\r\"
            exp_continue
        }
        -re {[Pp]assword} {
            send \"$ftnt_password\r\"
            exp_continue
        }
        {Login incorrect} {
            puts \"Login failed.\"
            exit 1
        }
        timeout {
            puts \"Timed out waiting for a response.\"
            exit 1
        }
        eof {
            puts stderr \"Successfully connected to $target.\"
            exit 1
        }
    }
"