#!/bin/bash
# set -x

if ! command -v jr &> /dev/null
then
    echo "jr command could not be found"
    exit
fi

fDebug=""
fExtendedSearch=""
fParams="-z"

while getopts "ed" opt; do
    case ${opt} in
        e)
            fExtendedSearch=true
            ;;
        d)
            fDebug=true
            ;;
        ?)
    esac
done

if [[ -n "$fExtendedSearch" ]]
then
    fParams="$fParams -e"
fi

if [[ -n "$fDebug" ]]
then
    fParams="$fParams -d"
fi

# Do not enclose $fParams in quotes
jr $fParams
