#!/usr/bin/expect

# Set the pattern to look for in the output
set pattern "$ "

# Set the number of iterations
set user_anotation "@@@@"
set max_iterations 100
set timeout -1
set url "https://172.16.67.186/downloads/"

# Check if an argument for max_iterations was provided
if {[llength $argv] > 0} {
    set max_iterations [lindex $argv 0]
}

for {set i 1} {$i <= $max_iterations} {incr i} {
    puts "$user_anotation Start of try #$i"
    # spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf
    spawn curl --max-time 259200 --insecure --trace-ascii - $url
    expect {
        "$pattern" {
        }
        timeout {
            puts "Timeout occurred. Pattern not found in the output."
        }
        eof {
            puts "$user_anotation End of try #$i"
        }
    }
    sleep 1
}

puts "Maximum number of iterations $max_iterations reached."

