#!/usr/bin/expect

# Set the pattern to look for in the output
set pattern "Access failed: 553"

# Set the number of iterations
set lftp_prompt "~> "
set exit_lftp_prompt "$ "
set timeout -1
set pattern_found 1
set max_iterations 100
set user_notation "@@@@"

# Check if an argument for max_iterations was provided
if {[llength $argv] > 0} {
    set max_iterations [lindex $argv 0]
}

spawn lftp -d -e "set ssl:verify-certificate no" -u test,test client2
expect "$lftp_prompt"

for {set i 1} {$i <= $max_iterations} {incr i} {
    # puts "-------> Start of try #$i"
    send "put fortiauto.pdf\r"

    expect {
        -re $pattern {
            # Pattern found
            puts "\n@@@@ Pattern '$pattern' Found in the output (Iteration $i)."
            set pattern_found 1
            exp_continue
        }
        timeout {
            puts "Timeout occurred. Pattern not found in the output."
        }
		$lftp_prompt {
            # puts "-------> End of command\n"
            if {$pattern_found == 0} {
                # puts "\n$user_notation Pattern '$pattern' Not Found in the output (Iteration $i)."
                break
            }
            set pattern_found 0
        }
    }

    # Sleep in seconds
    # sleep 1
}

if {$i >= $max_iterations} {
    puts "\n$user_notation Maximum number of iterations reached."
    exit 1
}

send "exit\r"
expect $exit_lftp_prompt

puts "\n$user_notation Pattern '$pattern' Not Found in the output (Iteration $i)."

# Get the size of the PDF file transfered to the server
set server_prompt "$ "
set expected_pdf_size 285442
set file_size 0
set ftp_server_path "/home/test"
set ftp_server_file_path "$ftp_server_path/fortiauto.pdf"

# Execute the stat command on client2 using SSH
puts -nonewline "$user_notation "
spawn ssh client2 "stat -c %s $ftp_server_file_path"
log_user 0
expect {
    -re {(\d+)} {
        set file_size $expect_out(1,string)
    }
}

log_user 1
# Check if the file size is as expected
if {$file_size == $expected_pdf_size} {
    puts "$user_notation The size of fortiauto.pdf is as expected: $file_size bytes."
} else {
    puts "$user_notation The size of fortiauto.pdf is not as expected. Actual size: $file_size bytes."
}
