#!/usr/bin/expect -f

set header_exp get_credentials

# Get the real directory of the script, resolving any symlinks
set script_path [file normalize [info script]]
# puts "script path is : $script_path"

# Determine the directory of the real script
set script_directory [file dirname $script_path]

# Source the other Expect script in the same directory
source "$script_directory/$header_exp"

set script_location "/tmp/git_fetch_repos"
set user_notation "@@@@"

if {![file exists $script_location]} {
    set script_contents {#!/bin/bash

# Define the directory containing your Git repositories
repos=(
    "$HOME/myGit/fos"
    "/data/fos2"
    "/data/fortiproxy"
)

# Function to update a Git repository
update_git_repo() {
    local repo_path="$1"

    echo -e  "\nUpdating repository: $repo_path"

    # Change to the repository directory
    cd "$repo_path" || exit 1

    # Check if it's a Git repository
    if [ -d ".git" ]; then
        git fetch --tags
        # Check if fetching was successful
        if [ $? -ne 0 ]; then
            echo "@@@@ Error fetching tags. Aborting."
            exit 1
        fi
        git fetch origin main
        # if [[ $repo_path == *"proxy"* ]] || [[ $repo_path == *"fpx"* ]]; then
        git fetch origin 7.0
        git rebase origin/7.0 7.0
        git fetch origin 7.2
        git rebase origin/7.2 7.2
    else
        echo "Not a Git repository: $repo_path"
    fi

    # Return to the original directory
    cd - &>/dev/null
}

# Loop through each repository and update it
for repo in "${repos[@]}"; do
    update_git_repo "$repo"
done
}

# Create the bash script
set script_file [open $script_location "w"]
puts $script_file $script_contents
close $script_file

# Set the executable permission for the script
exec chmod +x $script_location
}

proc common_expect_block {fa_pattern} {
    global pattern_found user_notation
    expect {
        {yes/no} {
            send "yes\r"
            exp_continue
        }
        -nocase -re "Username: " {
            send "$username\r"
            exp_continue
        }
        -nocase -re "Password:" {
            send "$password\r"
            exp_continue
        }
        -re $fa_pattern {
            puts "$user_notation Pattern '$fa_pattern' Found in the output."
            set pattern_found true
            exp_continue
        }
        -re "OTP: " {
            # Prompt for and read the FortiToken from the user
            # set timeout -1
            expect_user -re "(.*)\n"
            set token $expect_out(1,string)
            send "$token\r"
            exp_continue
        }
        timeout {
            puts "$user_notation Timed out! Have you set up your VPN?"
            exit 1
        }
        eof {}
    }
}

set fa_pattern "2fa_verify"
set pattern_found false
set timeout 180
spawn bash $script_location
common_expect_block $fa_pattern
if {$pattern_found == false} {
    exit 1
}

set fa_pattern "OTP validation failed:"
set pattern_found false
spawn ssh git@git-van.corp.fortinet.com 2fa_verify
common_expect_block $fa_pattern
if {$pattern_found == true} {
    exit 1
}

set fa_pattern "2fa_verify"
set pattern_found false
set timeout 180
spawn bash $script_location
common_expect_block $fa_pattern
if {$pattern_found == false} {
    exit 1
}

wait
