#!/bin/bash

# How to adjust the resolution of a VNC session?
# Say your local resolution is 1920x1080(width x height)
# and you may need to set the VNC resolution to around 2060x1080 to fit your screen
# How to adjust?
# Keep the height of the resolution the same, and only change the width
# Start by adjusting the width from 1080 to 2060 or more, and choose the one that best fits your screen.

resolution=2060x1080
# vncserver :9 -geometry 2060x1080
xrandr --output Virtual-1 --mode $resolution
