#!/bin/bash

scriptName=$(basename $0)
if [[ "$#" -lt 1 ]]; then
    echo "Usage: $scriptName <commit_path>"
    echo "Example: $scriptName ."
    exit 1
fi

# set the destination directory
destination_dir=/data/bugzilla/CC
diff_name="u.diff"

# get the source directory from the argument
source_dir=$1
if [ ! -d "$source_dir" ]; then
    echo "Error: $source_dir does not exist or is not a directory"
    exit 1
fi
cd "$source_dir" || exit
if [ ! -d .git ]; then
    echo "Error: $source_dir is not a git repository"
    exit 1
fi

if [ ! -d $destination_dir ]; then
    echo "Error: $destination_dir does not exist or is not a directory"
    exit 1
fi

git diff HEAD~1 HEAD > "$destination_dir/$diff_name"
cp fgtcoveragebuild.tar.xz "$destination_dir/"
if [ $? -ne 0 ]; then
    echo "Error: Failed to copy fgtcoveragebuild.tar.xz to $destination_dir"
    exit 1
fi
cp image.out "$destination_dir/"
if [ $? -ne 0 ]; then
    echo "Error: Failed to copy image.out to $destination_dir"
    exit 1
fi

cd - &> /dev/null || exit
bat -p "$destination_dir/$diff_name"
