#!/bin/bash

scriptName=$(basename $0)
if [[ "$#" < 1 ]]; then
    echo "Usage: $scriptName <commit_path>"
    echo "Example: $scriptName ."
    exit 1
fi

# set the destination directory
destination_dir=~/Public
diff_name="diff"

# get the source directory from the argument
source_dir=$1
cd $source_dir

# Run git diff and save the output to a file named "diff" in the destination directory
git diff HEAD~1 HEAD > "$destination_dir/$diff_name"

# Copy "fgtcoveragebuild.tar.xz" to the destination directory
cp fgtcoveragebuild.tar.xz "$destination_dir/"
if [ $? -ne 0 ]; then
    echo "Error: Failed to copy fgtcoveragebuild.tar.xz to $destination_dir"
    exit 1
fi

cp image.out "$destination_dir/"
if [ $? -ne 0 ]; then
    echo "Error: Failed to copy image.out to $destination_dir"
    exit 1
fi

cd - &> /dev/null
bat -p "$destination_dir/diff"
