#!/bin/bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
# shopt -s globstar

# bash command prompt
export PS1="\u@\h:\W\$ "

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# BELOW IS MYSELF CONFIGURATION.
# SET LS COLOR
# export LS_COLORS=$LS_COLORS:'di=0;35:':'ex=0;0'
export LS_COLORS=$LS_COLORS:'ex=0;0'
# MY USEFUL HANDY ALIAS. 
alias ls='ls --color=auto'
alias ll='ls -lF'
alias ll.='ls -alF'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias gdb='gdb -q'
alias cgdb='cgdb -q'
alias netstat='netstat -tuanp'
alias ag="ag --color-path='1;34' --color-line-number='0;8' --color-match='0;35'"
alias ack='ag'
# fix tmux utf8 issue
alias tmux='tmux -u'
# quick change directory
alias cdgit='cd $HOME/myGit'
alias cdsrc='cd /usr/local/src'

# SET LOCAL USEFUL VARIABLES.
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export SHELL=/bin/bash
export EDITOR=vim
# SET PATH VARIABLES.
PATH=$HOME/.usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
# export PKG_CONFIG_PATH=$HOME/.usr/lib/pkgconfig:$PKG_CONFIG_PATH
PKG_CONFIG_PATH=$HOME/.usr/lib/pkgconfig:/usr/local/lib/pkgconfig
LD_LIBRARY_PATH=$HOME/.usr/lib:$HOME/.usr/lib64:/usr/local/lib:/usr/local/lib64
export PATH
export PKG_CONFIG_PATH
export LD_LIBRARY_PATH

# SET HTTP/HTTPS PROXY.
# ssh -vv -ND 8080 [proxy_ip] [port]
# export https_proxy=socks5://127.0.0.1:8080
# export http_proxy=socks5://127.0.0.1:8080

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
else 
    # source full bash completion manually
	myBashCompTool=$HOME/.bash_completion.sh
	if [[ -f $myBashCompTool ]]; then
		source $myBashCompTool
	fi
fi
# loop to source extra completion for tmux/git etc
extraCompDir=$HOME/.completion.d
if [[ -d "$extraCompDir" ]]; then
    for file in `find $extraCompDir -regex ".*.bash" -type f`
    do
        source $file
    done
fi

# TEST IF COMMAND 'TMUX' EXIST.
if [[ "`which tmux`" != "" ]]; then
    if [[ "$TMUX" == "" ]]; then
        cat << "_EOF"
 _____   __  __   _   _  __  __
|_   _| |  \/  | | | | | \ \/ /
  | |   | |\/| | | | | |  \  /
  | |   | |  | | | |_| |  /  \
  |_|   |_|  |_|  \___/  /_/\_\

_EOF
        tmuxSession=`tmux ls`
        firstSession=`echo ${tmuxSession%%:*}`
        echo "tmux attach -t $firstSession"
    fi
else 
    echo "tmux does not exist."
fi
