""""""""""""""""""""""""""""
" BASIC CONFIG
""""""""""""""""""""""""""""""
syntax on
set number
set ruler
set laststatus=1
set autoindent
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set cinoptions={0,1s,t0,n-2,p2s,(03s,=.5s,>1s,=1s,:1s
set encoding=utf-8
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set fileencoding=utf-8
set termencoding=utf-8
set backspace=indent,eol,start
" Reference from /etc/vim/vimrc on Ubuntu
set nocompatible    " No vi compatible
set showmatch       " Show matching brackets.
set ignorecase      " Do case insensitive matching
set smartcase       " Do smart case matching
set nohlsearch        " Highlight searched word
set incsearch       " Incremental search
set hidden          " Hide buffers when they are abandoned
set mouse=a         " Enable mouse usage (all modes), or 'ni' for normal & insert
set noautochdir     " No need change dir with help of fuzzy finder tools
let g:solarized_termcolors=256
set background=dark
colorscheme solarized
" set showcmd       " Show (partial) command in status line.
" set autowrite     " Automatically save before commands like :next and :make
filetype plugin indent on
" Jump to the last position when reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$")
                \ | exe "normal! g'\"" | endif
endif
" Let .php use html snippets
" autocmd filetype php set filetype=php.html.js
"------ :help ins-completion-menu -----
set pumheight=12      " maximum height of popup menu
set shell=/bin/bash   " set vim default shell
let mapleader=';'     " leader key, default is '\'
set t_Co=256          " number of colors
" Tip: below two lines handle characters over 80c
" highlight OverLength ctermbg=33 ctermfg=Grey
" match OverLength /\%81v.\+/
set background=dark
"------ private under ~/.vim/colors -----
" :colorscheme darkcoding

""""""""""""""""""""""""""""""
" BASIC KEYBIND
""""""""""""""""""""""""""""""
" map: recursive mapping, case ignorance
" nnoremap: no recursive mapping, avoid below shortcut key mapping
" Important: <leader>lw will slow down heavily for <leader>l
" <S-...> Shift +
" <C-...> Control +
" <M-...> Alt +
" <A-...> as <M-...>
" <Esc>   Escape
" <Up>    Arrow up
" <Tab>   Tab
" <CR>    Carriage Return, enter
" <Space> Space
" <k0> - <k9> small keyboard 0 - 9
cmap w!! w !sudo tee %
set pastetoggle=<F12>
nmap <F10> :set invnumber<CR>
nmap <leader>k :mark<Space>
" Inverse Highlight searched word
"
" Removing trailing white spaces
nmap <C-G> :%s/\s\+$//gc<CR>
" Easy vim manipulator
nmap <leader>R :source ~/.vimrc<CR>
" nmap <silent> <leader>q       :qall!<CR>
nmap <silent> <leader>q       :q<CR>
nmap <silent> <leader>w       :w<CR>
imap <C-D> <ESC>dd
" Set stty -ixon on ~/.bashrc
" nnoremap <leader>W       :write!<CR>
nnoremap <C-S>            :write<CR>
inoremap <C-S>       <ESC>:write<CR>
vnoremap <C-S>       <ESC>:write<CR>
" Jump between buffers
nmap <leader>1 :buffer1<CR>
nmap <leader>2 :buffer2<CR>
nmap <leader>3 :buffer3<CR>
nmap <leader>4 :buffer4<CR>
nmap <leader>5 :buffer5<CR>
nmap <leader>6 :buffer6<CR>
nmap <leader>7 :buffer7<CR>
nmap <leader>8 :buffer8<CR>
nmap <leader>9 :buffer9<CR>
nmap <leader>d :bdelete
" Jump to previous/next buffer
nmap <leader>- <C-O><CR>
nmap <leader>+ <C-I><CR>
set clipboard=unnamedplus,unnamed
