#!/bin/bash

# Default to updating the current session
user_notation="@@@@"

usage() {
    scriptName=$(basename "$0")
    cat << _EOF
Usage: $scriptName [options]
       $scriptName [-a] [-h]

Options:
    -h      Print this help message

Example:
    $scriptName     // Update all windows only in the current session
    $scriptName -h  // Print this help message

_EOF
    exit 0
}

# Parse command-line options
while getopts "h" opt; do
    case ${opt} in
        h )
            usage
            ;;
        \? )
            echo "$user_notation Invalid option: -$OPTARG" 1>&2
            ;;
    esac
done

# Shift to process non-option arguments. New $1, $2, ..., $@
shift $((OPTIND - 1))
if [[ $# -gt 0 ]]; then
    echo "$user_notation Illegal non-option arguments: $@"
    exit
fi

maximize_windows_in_current_session() {
    # Get the list of all windows in the session
    windows=$(tmux list-windows -F '#{window_index}')

    for win in $windows; do
        # Switch to the window
        tmux select-window -t "$win"
        # Resize the current window to maximum size
        tmux resize-window -A
    done
}

# Record the current session and window
current_window=$(tmux display-message -p '#I')

maximize_windows_in_current_session

# Switch back to the original session and window
tmux select-window -t "$current_window"
