# On macOS, initialize Homebrew before sourcing .bashrc
if [[ $(uname -s) == 'Darwin' ]]; then
    if [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
