# Bash completion for codex (OpenAI Codex CLI).
#
# codex's own completion does the work: `codex completion bash` (generated by
# clap) knows every subcommand, each one's own options, and their current
# possible values. A hand-kept copy of those lists went stale: written
# 2026-05-01, it never learnt `delete`, `archive`, `agents` and six more, kept
# offering the removed `app` and `mcp-server`, and `-a untrusted`.
#
# On top of it this file adds what codex's script cannot know:
#   - the wrapper flags track-files/bashrc strips before codex sees them:
#       --auto-approve / -y  =>  launch a ja daemon to answer approval prompts
#   - model names for -m / --model, from codex's own model cache (its help
#     only says <MODEL>)
# and keeps the jc/ja/claude convention: a bare word completes subcommands
# (or values), -<TAB> short options only, --<TAB> long ones.
#
# The generated script is 230 KB and takes ~0.3 s to produce, so it is neither
# sourced at shell startup nor produced per TAB: it is written once per codex
# install to the cache dir, keyed on the binary's inode and ctime (an upgrade
# replaces the file, changing both), and sourced at the first TAB.

_codex_load_generated() {
    local bin key cache="${XDG_CACHE_HOME:-$HOME/.cache}/codex-completion.bash" nvm_bins
    # An interactive shell gets node's bin on PATH only once the bashrc wrapper
    # first launches claude or codex (it loads nvm lazily), so `codex <TAB>` in a
    # fresh shell found nothing. The newest nvm install is the fallback, the same
    # one jcl's completion falls back to for claude.
    if ! bin=$(type -P codex); then
        nvm_bins=( "${NVM_DIR:-$HOME/.nvm}"/versions/node/*/bin/codex )
        bin=${nvm_bins[${#nvm_bins[@]}-1]}
    fi
    [[ -x $bin ]] || return 1
    key="# $bin $(stat -L -c '%i %Z' "$bin" 2>/dev/null || stat -L -f '%i %c' "$bin" 2>/dev/null)"
    [[ $_codex_generated_key == "$key" ]] && return 0
    if [[ $(head -n 1 "$cache" 2>/dev/null) != "$key" ]]; then
        mkdir -p "${cache%/*}" 2>/dev/null
        # codex prints housekeeping warnings on stderr; only stdout is the script.
        # _codex_listed is what `codex --help` lists, for the first word: the
        # generated script also offers hidden commands (tcp-tunnel,
        # stdio-to-uds, ...) and the aliases e and a.
        { printf '%s\n' "$key"
          "$bin" completion bash 2>/dev/null
          printf '_codex_listed=" %s"\n' "$("$bin" --help 2>/dev/null | awk '
              /^Commands:/ { listed = 1; next }
              /^[A-Z][A-Za-z ]*:$/ { listed = 0 }
              listed && /^  [a-z]/ { printf "%s ", $1 }')"
        } > "$cache.$$" 2>/dev/null
        if ! grep -q '^_codex()' "$cache.$$" 2>/dev/null; then
            rm -f "$cache.$$"
            return 1
        fi
        mv -f "$cache.$$" "$cache"
    fi
    source "$cache" || return 1
    # The script ends by registering its own _codex for codex: put ours back
    complete -F _codex_complete -o bashdefault -o default codex
    _codex_generated_key=$key
}

# The models /model offers: codex keeps the list it fetched in models_cache.json
_codex_models() {
    local cache="${CODEX_HOME:-$HOME/.codex}/models_cache.json"
    [[ -r $cache ]] || return 0
    if type -P jq >/dev/null; then
        jq -r '.models[]? | select(.visibility != "hide") | .slug' "$cache" 2>/dev/null
    else
        python3 -c 'import json, sys
for m in json.load(open(sys.argv[1])).get("models", []):
    if m.get("visibility") != "hide":
        print(m["slug"])' "$cache" 2>/dev/null
    fi
}

_codex_complete() {
    local cur=${COMP_WORDS[COMP_CWORD]} prev=${COMP_WORDS[COMP_CWORD-1]} i
    COMPREPLY=()

    if [[ $prev == -m || $prev == --model ]]; then
        COMPREPLY=( $(compgen -W "$(_codex_models)" -- "$cur") )
        return 0
    fi

    _codex_load_generated && _codex "$@"

    case $cur in
        --*)
            COMPREPLY+=( $(compgen -W "--auto-approve" -- "$cur") )
            ;;
        -*)
            for i in "${!COMPREPLY[@]}"; do
                [[ ${COMPREPLY[i]} == --* ]] && unset 'COMPREPLY[i]'
            done
            COMPREPLY+=( $(compgen -W "-y" -- "$cur") )
            ;;
        *)
            for i in "${!COMPREPLY[@]}"; do
                case ${COMPREPLY[i]} in
                    -* | \[* | \<*)  # options, and placeholders such as [PROMPT]
                        unset 'COMPREPLY[i]' ;;
                    *)
                        [[ $COMP_CWORD == 1 && -n $_codex_listed
                           && $_codex_listed != *" ${COMPREPLY[i]} "* ]] && unset 'COMPREPLY[i]' ;;
                esac
            done
            ;;
    esac
    COMPREPLY=( "${COMPREPLY[@]}" )
}

complete -F _codex_complete -o bashdefault -o default codex
