#!/usr/bin/expect -f

set fgt_name [lindex $argv 0]
if {[llength $argv] == 0} {
    set fgt_name "fgt1"
}

# Set your SSH credentials
set user "admin"
set port "22"

# Define the expected command prompt
set prompt "# "

# Check if fgt_name is "fgt1" and assign the appropriate IP address
if {$fgt_name == "fgt1"} {
    set fgt_address "192.168.101.1"
} elseif {$fgt_name == "fgt2"} {
    # Add more conditions for different devices if needed
    set fgt_address "192.168.103.1"
    # You can continue adding more conditions for other device names
    # elseif {$fgt_name == "fgt3"} {
    #     set fgt_address "192.168.100.3"
    # }
} else {
    puts "Unknown FortiGate device: $fgt_name"
    exit 1
}

# Spawn the SSH process
spawn ssh -p $port $user@$fgt_address

expect {
    "yes/no" {
        send "yes\r"
    }
    -re $prompt {
	send "\r"
    }
}

expect -re $prompt
send "sys sh\r"
expect -re $prompt
send "ps | grep -i 'wad 17' | grep -v grep\r"

# Expect the output and capture it in a variable
expect -re $prompt
set ps_output $expect_out(buffer)

# Use regular expressions to extract the PID
set pid ""
# 18597     0       0       S       /bin/wad 17 0
regexp {(\d+) +\d+ +\d+ +\S+ +/bin/wad 17 0} $ps_output match pid

# start gdbserver
set timeout -1
send "gdbserver 0.0.0.0:444 --attach $pid\r"

# \x03 is used to send a Ctrl-C signal when the trap detects the SIGINT (Ctrl-C) signal.
trap {
    send \x03
    send_user "You pressed Ctrl+C\n"
} SIGINT

# interact
expect -re $prompt
# send "exit\r"
