#!/usr/bin/expect

# Set the pattern to look for in the output
set pattern "got 553"
# set pattern "226 Transfer complete"

# Set the number of iterations
set max_iterations 100
set timeout -1

# Check if an argument for max_iterations was provided
if {[llength $argv] > 0} {
    set max_iterations [lindex $argv 0]
}

for {set i 1} {$i <= $max_iterations} {incr i} {
# spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf --trace-ascii -
        spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf

            expect {
                -re $pattern {
                    # Pattern found
                    puts "\nPattern '$pattern' found in the output (Iteration $i)."
                    set pattern_found 1
                    exp_continue
                }
                timeout {
                    puts "\nTimeout occurred. Pattern not found in the output."
                }
		 eof {
                    puts "\n------------------ End of command output ------------------"
                    if {$pattern_found == 0} {
                        puts "\nPattern '$pattern' not found in the output (Iteration $i)."
                        exit
                    }
                    set pattern_found 0
                }
            }

    # Wait for the spawned process to complete
    wait

    # Sleep for a while before the next iteration
    after 2000 # 1 second
}

puts "\nMaximum number of iterations reached. Pattern not found in the output."

