#!/usr/bin/expect

# Set the pattern to look for in the output
set pattern "got 553"
set pattern "226 Transfer complete"

# Set the number of iterations
set max_iterations 100
set timeout -1

# Check if an argument for max_iterations was provided
if {[llength $argv] > 0} {
    set max_iterations [lindex $argv 0]
}

for {set i 1} {$i <= $max_iterations} {incr i} {
        # spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf --trace-ascii -
        spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf

        expect {
            -re $pattern {
                # Pattern found
                puts "\n\nPattern '$pattern' found in the output (Iteration $i)."
                exit
            }
            timeout {
                puts "\nTimeout occurred. Pattern not found in the output."
            }
            eof {
                puts "\nEnd of command output."
            }
        }

    # Wait for the spawned process to complete
    wait

    sleep 1
}

puts "Maximum number of iterations reached."
