#!/usr/bin/expect

# Set the pattern to look for in the output
set pattern "Access failed: 553"

# Set the number of iterations
set prompt "~> "
set exit_prompt "$ "
set timeout -1
set pattern_found 0
set max_iterations 100

# Check if an argument for max_iterations was provided
if {[llength $argv] > 0} {
    set max_iterations [lindex $argv 0]
}

spawn lftp -d -e "set ssl:verify-certificate no" -u test,test client2
expect "$prompt"

for {set i 1} {$i <= $max_iterations} {incr i} {
    # puts "-------> Start of try #$i"
    send "put fortiauto.pdf\r"

    expect {
        -re $pattern {
            # Pattern found
            puts "\n@@@@ Pattern '$pattern' Found in the output (Iteration $i)."
            set pattern_found 1
            exp_continue
        }
        timeout {
            puts "Timeout occurred. Pattern not found in the output."
        }
		$prompt {
            # puts "-------> End of command\n"
            if {$pattern_found == 0} {
                # puts "\n@@@@ Pattern '$pattern' Not Found in the output (Iteration $i)."
                break
            }
            set pattern_found 0
        }
    }

    # Sleep in seconds
    # sleep 1
}

send "exit\r"
expect $exit_prompt
if {$i < $max_iterations} {
    puts "\n@@@@ Pattern '$pattern' Not Found in the output (Iteration $i)."
} else {
    puts "\n@@@@ Maximum number of iterations reached."
}
