#!/usr/bin/expect

# Set the pattern to look for in the output
set pattern "got 553"
# set pattern "226 Transfer complete"

# Set the number of iterations
set max_iterations 100
set timeout -1

# Check if an argument for max_iterations was provided
if {[llength $argv] > 0} {
    set max_iterations [lindex $argv 0]
}

for {set i 1} {$i <= $max_iterations} {incr i} {
    puts "-------> Start of try #$i"
    # spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf --trace-ascii -
    # spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf
    spawn curl -k --ftp-ssl -u test:test ftp://172.16.67.182 -T /home/corsair/Uploads/fortiauto.pdf -v

    expect {
        -re $pattern {
            # Pattern found
            puts "\n@@@@ Pattern '$pattern' Found in the output (Iteration $i)."
            set pattern_found 1
            exp_continue
        }
        timeout {
            puts "Timeout occurred. Pattern not found in the output."
        }
		eof {
            # puts "-------> End of command\n"
            if {$pattern_found == 0} {
                puts "\n@@@@ Pattern '$pattern' Not Found in the output (Iteration $i)."
                exit
            }
            set pattern_found 0
        }
    }

    # Wait for the spawned process to complete
    wait

    # sleep 1
}

puts "Maximum number of iterations reached."
