#!/usr/bin/expect -f

set header_exp get_credentials

# Get the real directory of the script, resolving any symlinks
set script_path [file normalize [info script]]

# Determine the directory of the real script
set script_directory [file dirname $script_path]

# Source the other Expect script in the same directory
source "$script_directory/$header_exp"

# Set a custom timeout value in seconds (e.g., 180 seconds)
set custom_timeout 180

# Set the value of the "mode" variable
# set mode "FGT_601F"
set mode "FGT_VM64_KVM"

# Spawn your target script or command using the "mode" variable
spawn rb_genco_git post --username $username

# Set the timeout value for this specific interaction
set timeout $custom_timeout

expect {
    "Username: " {
        send "$username\r"
        exp_continue
    }
    "Password: " {
        send "$password\r"
        exp_continue
    }
    "Password for '$username': " {
        send "$password\r"
        exp_continue
    }
    timeout {
        # Handle timeout actions, such as error handling
        puts "Timed out waiting for a response."
        exit 1
    }
}

# Continue with the script or additional interactions

