#!/bin/bash

# List all running VMs
vm_list=$(sudo virsh list --name)

# Loop through the list of VMs
for vm in $vm_list; do
    # Check if the VM is running
    if sudo virsh domstate "$vm" | grep -q "shut"; then
        echo "VM '$vm' is already shut down."
	continue
    fi

    # Shut down the VM if it's not already shut down
    sudo virsh shutdown "$vm"
    if [ $? -ne 0 ]; then
        echo "Failed to start VM: $vm"
    fi
done
